name: Quarto Render and Publish

permissions:
    contents: write
    pages: write

on:
  workflow_call:
    inputs:
      R_version:
        type: string
        description: 'R version to use'
        required: false
        default: '4.3.1'
      system_dependencies:
        type: string
        description: 'List of system dependencies to install'
        required: false
        default: |
          libx11-dev \
          make \
          zlib1g-dev \
          pandoc \
          libicu-dev \
          libpng-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          libxml2-dev

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ inputs.R_version }}
          use-public-rspm: true
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
          ${{ inputs.system_dependencies }}
      
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
    
      - name: Ensure gh-pages branch exists
        run: |
          if ! git ls-remote --exit-code --heads origin gh-pages; then
            git checkout --orphan gh-pages
            git rm -rf .
            touch .nojekyll
            git add .nojekyll
            git commit -m "Initialize gh-pages branch"
            git push origin gh-pages
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
